Dev changes [0e0b1f05fa542c416f143cfccec34aad5535b1ba]

diff --git a/nnpi_os_buildroot/board/sph/rootfs-overlay/usr/local/bin/init_ice_driver b/nnpi_os_buildroot/board/sph/rootfs-overlay/usr/local/bin/init_ice_driver
--- a/nnpi_os_buildroot/board/sph/rootfs-overlay/usr/local/bin/init_ice_driver
+++ b/nnpi_os_buildroot/board/sph/rootfs-overlay/usr/local/bin/init_ice_driver
@@ -46,6 +46,11 @@ check_ices() {
 
                 INTEL_NNPI_ARGS="${INTEL_NNPI_COMMON_ARGS} icemask_user=$mask"
                 modprobe intel_nnpi $INTEL_NNPI_ARGS
+		if [ $? !=  0 ]
+		then
+			echo "Failed to insmod intel_nnpi driver - aborting!"
+			exit 1
+		fi
 #               echo "loaded intel_nnpi with args: $INTEL_NNPI_ARGS"
                 good_ICE=1
                 j=0
